# Generated by Django 2.2.14 on 2020-08-02 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0002_auto_20200802_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletteruser',
            name='date_added',
        ),
    ]
