# Generated by Django 3.0.8 on 2020-08-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0003_remove_newsletteruser_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=200)),
                ('pdf', models.FileField(upload_to='documents/event_bg/')),
            ],
        ),
    ]
