# Generated by Django 2.2.15 on 2020-08-14 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0004_newsletterdoc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterDoc',
        ),
    ]
