# Generated by Django 3.0.5 on 2020-04-18 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200418_1842'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eventss',
            new_name='Event',
        ),
        migrations.AlterModelTable(
            name='event',
            table='Event',
        ),
    ]
