# Generated by Django 3.0.5 on 2020-04-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200418_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('branch', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EE', 'EE'), ('MECH', 'MECH'), ('PE', 'PE'), ('IT', 'IT'), ('CE', 'CE')], max_length=20)),
                ('year', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=20)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'Participant',
            },
        ),
    ]
