# Generated by Django 3.0.5 on 2020-05-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='present',
            field=models.CharField(default='No', max_length=10),
        ),
    ]
