# Generated by Django 2.2.12 on 2020-06-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200626_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='present',
            field=models.CharField(default='No', editable=False, max_length=10),
        ),
    ]
