# Generated by Django 2.2.12 on 2020-06-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200628_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='present',
            field=models.CharField(default='No', max_length=10, null=True),
        ),
    ]
