# Generated by Django 2.2.12 on 2020-06-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200628_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='time',
            field=models.TimeField(default=None),
        ),
    ]
