# Generated by Django 2.2.12 on 2020-06-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_participant_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='time',
            field=models.TimeField(default=None, null=True),
        ),
    ]
