# Generated by Django 2.2.12 on 2020-06-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20200628_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='time',
            field=models.TimeField(),
        ),
    ]
