# Generated by Django 2.2.12 on 2020-06-28 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_event_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='time',
        ),
    ]
