# Generated by Django 2.2.12 on 2020-06-28 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_remove_participant_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
