# Generated by Django 2.2.12 on 2020-06-29 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_clicks_body'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clicks',
            new_name='Click',
        ),
    ]
