# Generated by Django 2.2.12 on 2020-06-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_auto_20200629_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='body',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='click',
            name='images',
            field=models.FileField(null=True, upload_to='images/past_events_images/'),
        ),
    ]
