# Generated by Django 2.2.14 on 2020-07-24 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
