# Generated by Django 2.2.14 on 2020-08-09 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
