# Generated by Django 2.2.15 on 2020-08-15 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_delete_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
